spring:
    application:
        name: desafio-tecnico-syonet
    datasource:
        url: jdbc:h2:mem:syonet
        username: ${H2_USER}
        password: ${H2_PASSWORD}
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
        hibernate:
            ddl-auto: none
    flyway:
        enabled: true
        baseline-on-migrate: true
        validate-on-migrate: true
        locations: classpath:db/migration

    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_LOGIN}
        password: ${MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enabled: true
                        required: true
    thymeleaf:
        prefix: classpath:/email/
        suffix: .html