create table cliente (
    id bigint generated by default as identity primary key,
    email varchar(255) not null,
    nascimento date,
    nome varchar(255) not null
);

create table noticia (
    id bigint generated by default as identity primary key,
    descricao varchar(255) not null,
    processado boolean not null,
    titulo varchar(255) not null,
    url varchar(255)
);